### ISSUE TITLE
check_unapplied error while using migrate_schemas command with django 3.1

### ISSUE THREAD

**Issue by NicoZeiss** [django-tenants/django-tenants#461] opened 2020-08-13 15:23 UTC
I have upgraded my project from Django 2.2 to Django 3.1, with django-tenants 3.1.0
I encounter an issue when I use `migrate_schemas` command.

Here is the last line of the traceback:
```
Traceback (most recent call last):
 ...
  File "C:\Users\devp4\Documents\Repositories\Cashup\venv\lib\site-packages\django\core\management\commands\migrate.py", line 151, in handle
    exit_dry = plan and options['check_unapplied']
KeyError: 'check_unapplied'
```
My solution was to add these lines to `django-tenants/management/commands/migrate_schemas.py`:
```
def add_arguments(self, parser):
    ...
    parser.add_argument(
                '--check', action='store_true', dest='check_unapplied',
                help='Exits with a non-zero status if unapplied migrations exist.',
            )
```
Am I missing something? Should I open a PR?

**Comment by harpiya** [comment] 2020-08-13 23:29
django-tenans 3.1.0 seems to be compatible with django 3.0.9. Django 3.1 update has been made in Github version. You can update and try the django-tenants application with the github repository. you probably won't get an error.

**Comment by infosrabah** [comment] 2020-08-15 22:21
If you have Django 3.1 and when you install django-tenants 3.2.0 the actual github repository version, django falls back to version 3.0.9

github version of django-tenants it's not yet compatible django 3.1

**Comment by tomturner** [comment] 2020-08-24 09:36
Close as it a duplicate of #434

**Closed by tomturner** 2020-08-24 09:36 UTC
